### PR TITLE
Remove Network ACL

### PR DESCRIPTION
**Pull request by k2nr**
**Do not merge for now**

Removed Network ACL from the network stack. Currently we don't need this change but in the future we will this change to support VPC-mode task networking where ECS task uses its own ENI

### CODE REVIEW

**Comment by essa** [comment]
Why is Network ACL related with VPC-mode?

**Comment by k2nr** [comment]
In bridge mode (which we currently use), each task has a bridge network interface that's connected to host's ENI, and host maps container port to host port, for example nginx container listens on port 80 and host maps it to host's 10000. In this case, port 10000 is the exposed port for the nginx container.
In VPC mode, each task has a dedicated ENI, so, if nginx container listens on port 80, that's ENI's port 80.

In bridge mode, we know that hosts do not listen on port ~ 1024 except for some special ports, which is why we filtered out most well-known ports with NACL. but in VPC mode, tasks can listen on any ports, some of which may need to be exposed to public subnets.

**Comment by essa** [comment]
I see, thanks for detailed explanation.

LGTM 👍

**Comment by davidsiaw** [comment]
@k2nr I'm gonna close this as well because its old and it doesn't look like we need it for now.

**Pull request closed without merging**
