### PR TITLE
Update AMI of container and bastion instances to 2.0.20210301

### PR DESCRIPTION
**Pull request by essa**
This PR will update the ami of container instances as following page.

- [Amazon ECS\-optimized AMIs \- Amazon Elastic Container Service](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html)

And it also updates ami for bastion image.

- https://ap-northeast-1.console.aws.amazon.com/systems-manager/parameters/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2/description?region=ap-northeast-1

### CODE REVIEW

**Comment by degicat** [comment]
@k2nr please review this

**Comment by degicat** [comment]
@Yuuki77 please review this

**Comment by Yuuki77** [comment]
@essa I checked and it looks good to me for `ECS_OPTIMIZED_AMI_IDS`
but how can I check for  bastion image?
I only can see the one id when I clicked 
 `https://ap-northeast-1.console.aws.amazon.com/systems-manager/parameters/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2/description?region=ap-northeast-1` 🙏

**Comment by essa** [comment]
@Yuuki77 
Thanks for checking!

Please change the region in the upper left
スクリーンショット 2021-03-08 14 36 58

**Comment by Yuuki77** [comment]
@essa Thank you for the explanations 🙏 
checked and looks good to me 👍

**Review by Yuuki77 — APPROVED** [review]
LGTM!

**Comment by essa** [comment]
Thanks!

**Pull request merged**
