### PR TITLE
Update AMI of container and bastion instances to Amazon Linux 2.0.20230428

### PR DESCRIPTION
**Pull request by matafc**
This PR will update the AMIs of the container instances as described in this guide:

[Amazon ECS-optimized AMIs - Amazon Elastic Container Service](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html)

ECS AMI SSM path: https://ap-northeast-1.console.aws.amazon.com/systems-manager/parameters/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id/description?region=ap-northeast-1

And it also updates the AMI for the bastion image.

Bastion AMI SSM path: https://ap-northeast-1.console.aws.amazon.com/systems-manager/parameters/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2/description?region=ap-northeast-1

### CODE REVIEW

**Comment by degikko** [comment]
@wyugue can you help us review this PR, please?

**Review by essa — APPROVED** [review]
LGTM 👍 

Could you add the ssm path of recommended ECS optimized AMI next time?
https://ap-northeast-1.console.aws.amazon.com/systems-manager/parameters/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id/description?region=ap-northeast-1&tab=Table#list_parameter_filters=Name:Contains:%2Faws%2Fservice%2Fecs%2Foptimized-ami%2Famazon-linux-2%2Frecommended

**Comment by matafc** [comment]
Updated. Please note the version is a little different between https://ap-northeast-1.console.aws.amazon.com/systems-manager/parameters/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id/description?region=ap-northeast-1 and https://ap-northeast-1.console.aws.amazon.com/systems-manager/parameters/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/description?region=ap-northeast-1 but I'll use the parameter with more info, that is what the script is using.

**Comment by essa** [comment]
@matafc 
> the version is a little different between

I think it's difference of ECS ami version and Amazon Linux2 ami version

> "image_version":"2.0.20230428"

This is the ECS optimized ami version. It is updated when ECS agent or docker is updated. Sometimes it will be newere than the source_image_version.

> "source_image_name":"amzn2-ami-minimal-hvm-2.0.20230418.0-x86_64-ebs"

This is the plain Amazon Linux2 version from which ECS optimized AMI was made.

**Pull request merged**
