### PR TITLE
Use Amazon Time Sync Service instead of built-in ntpd

### LINKED ISSUE #441: Use Amazon Time Sync Service for instances time sync
https://aws.amazon.com/blogs/aws/keeping-time-with-amazon-time-sync-service/

I need to check if the service is PCIDSS compliant. If it is, we can remove the dedicated NTP server from PCIDSS plugin

### PR DESCRIPTION
**Pull request by k2nr**
Fixes #441 

The motivation is that with the time sync service, we don't need the complex NTP configuration in PCIDSS plugin (a dedicated NTP server, hot-standby ENI, right ENI selection)

the following error occurred during the initialization

```
+ service chronyd start
Generating chrony command key: tr: write error: Broken pipe
tr: write error
[  OK  ]
```

but I confirmed that the right chrony key is generated & stroed in the right place (/etc/chrony.keys)

the instance in test district with this configuration has been running for a few days and chrony correctly syncing time

### CODE REVIEW

**Comment by k2nr** [comment]
hard to debug because the error doesn't occur when I login via `ssh` and run `sudo service chronyd start` :disappointed:

**Comment by k2nr** [comment]
I guess `/dev/urandom`'s entropy is not enough to generate the requested bytes :thinking:

**Comment by k2nr** [comment]
OK although there is "broken pipe" error, correct key is appended to the key file. I'm not sure why the "broken pipe" happen but we can safely ignore it

**Comment by k2nr** [comment]
Once this is merged and we confirm it works fine, I'll remove all code that are related to NTP. we no longer need the dedicated NTP server (PCIDSS plugin), security group (both inbound and outbound), network ACL, etc

**Comment by k2nr** [comment]
Updated the description. @essa  can you review when you have time?

**Comment by k2nr** [comment]
I just followed this doc https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html#configure-amazon-time-service

**Comment by essa** [comment]
@k2nr 

I see no configuration for `chrony.conf`. 
Is the default of the chrony server in AWS (`169.254.169.123`)?

**Comment by k2nr** [comment]
Amazon Linux's chrony package uses `169.254.169.123` by default. Here's the `chrony.conf` in my test district:

```
[ec2-user@ip-10-233-1-144 ~]$ sudo cat /etc/chrony.conf | head
# use the local instance NTP service, if available
server 169.254.169.123 prefer iburst

# Use public servers from the pool.ntp.org project.
# Please consider joining the pool (http://www.pool.ntp.org/join.html).
pool 2.amazon.pool.ntp.org iburst

# Record the rate at which the system clock gains/losses time.
driftfile /var/lib/chrony/drift
```

**Comment by essa** [comment]
> Amazon Linux's chrony package uses 169.254.169.123 by default.
Great, thanks!

LGTM 👍

**Comment by k2nr** [comment]
Thanks for the review! I'll keep the test cluster running until next Monday and will apply this to staging if there's no problem found

**Pull request merged**
