### PR TITLE
Enable VPC flow logs

### PR DESCRIPTION
**Pull request by k2nr**
Adds `AWS::EC2::FlowLog` resource associating to the VPC.

### CODE REVIEW

**Comment by k2nr** [comment]
Test on the test VPC. this configuration works

**Comment by k2nr** [comment]
@essa can you review when you have time?

**Comment by essa** [comment]
LGTM 👍

**Comment by k2nr** [comment]
I misunderstood how GuardDuty works. We don't need to add this configuration because GuardDuty fetches VPC flow logs through AWS internal mechanism. I don't see any good use case for VPC flow logs other than GuardDuty so I'm closing this PR for now

**Pull request closed without merging**
