### PR TITLE
Rails build

### PR DESCRIPTION
**Pull request by davidsiaw**
This PR moves more stuff from the dockerfiles repo up to here, since barcelona depends on these too.

Note to reviewer: Please ping me if anything stands out to you that seems slightly weird. This pushes images that will be available publicly so this review is more an audit to check if there are things that should not be inside.

Functionality-wise you can look at https://gallery.ecr.aws/degica/rails-buildpack to see what it has built.

### CODE REVIEW

**Comment by degicat** [comment]
@dopin can you help us review this PR, please?

**Comment by degicat** [comment]
@essa can you help us review this PR, please?

**Review by dopin — APPROVED** [review]
LGTM ✨ 

I ran the following command to confirm that there are no changes in the Dockerfiles.

```bash
 diff -u dockerfiles/rails-base/alpine/2.4/Dockerfile ../dockerfiles/rails-base/alpine/Dockerfile
 diff -u dockerfiles/rails-base/debian/2.3/Dockerfile ../dockerfiles/rails-base/alpine/Dockerfile
 diff -u dockerfiles/rails-base/debian/2.3/Dockerfile ../dockerfiles/rails-base/debian/2.3/Dockerfile
 diff -u dockerfiles/rails-base/debian/2.4/Dockerfile ../dockerfiles/rails-base/debian/2.4/Dockerfile
 diff -u dockerfiles/rails-base/debian/2.5/Dockerfile ../dockerfiles/rails-base/debian/2.5/Dockerfile
 diff -u dockerfiles/rails-base/example/Dockerfile ../dockerfiles/rails-base/example/Dockerfile
 diff -u dockerfiles/rails-base/example/Dockerfile.development ../dockerfiles/rails-base/example/Dockerfile.development
 diff -u dockerfiles/rails-base/example/docker-compose.yml ../dockerfiles/rails-base/example/docker-compose.yml
 diff -u dockerfiles/rails-buildpack/2.4/Dockerfile ../dockerfiles/rails-buildpack/2.4/Dockerfile
 diff -u dockerfiles/rails-buildpack/2.6.5-stretch/Dockerfile ../dockerfiles/rails-buildpack/2.6.5-stretch/Dockerfile
 diff -u dockerfiles/rails-buildpack/2.6/Dockerfile ../dockerfiles/rails-buildpack/2.6/Dockerfile
 diff -u dockerfiles/rails-buildpack/2.7.3/Dockerfile ../dockerfiles/rails-buildpack/2.7.3/Dockerfile
 diff -u dockerfiles/rails-buildpack/2.7/Dockerfile ../dockerfiles/rails-buildpack/2.7/Dockerfile
```

**Comment by essa** [comment]
@davidsiaw 
Why are we moving these sources?

> since barcelona depends on these too

I can understand that [barcelona depends on rails-buildpack:2.6](https://github.com/degica/barcelona/blob/master/Dockerfile#L1) but barcelona is not depend other images.
And, if it depends on those images, why should the dockerfiles be in the same repository?

**Comment by davidsiaw** [comment]
@essa

> @davidsiaw Why are we moving these sources?
> 
> > since barcelona depends on these too
> 
> I can understand that [barcelona depends on rails-buildpack:2.6](https://github.com/degica/barcelona/blob/master/Dockerfile#L1) but barcelona is not depend other images. And, if it depends on those images, why should the dockerfiles be in the same repository?

Because I moved them from our dockerfiles repository all together. Barcelona depends on a subset of these dockerfiles, but all the dockerfiles are basically base images that we use.

We can move all the dockerfiles to another repository as well (it might make more sense that way) or create a barcelona organization and put them there since it has grown to involve more than one program.

**Comment by essa** [comment]
@davidsiaw 

Thanks for comment, but I still can't see the value of moving them.

Is there any problems with current https://github.com/degica/dockerfiles repository?
And how dose this PR resolve it?

**Comment by davidsiaw** [comment]
@essa It seemed cleaner to have all the dockerfiles in one place

**Comment by essa** [comment]
@davidsiaw 
Yes, having all the **common shared** dockerfiles in one place is a clean way and it is the purpose of https://github.com/degica/dockerfiles.
[dockerfiles directory in this repo](https://github.com/degica/barcelona/tree/master/dockerfiles) contains only dockerfiles used by only barcelona. No other app uses these docker images.

So I think current way is the best way.

**Comment by davidsiaw** [comment]
@essa sounds good then, i will move the workflow yaml to the dockerfile repo instead

**Comment by essa** [comment]
Thank you! 🙇‍♂️

**Pull request closed without merging**
