### PR TITLE
AMI update to Amazon Linux 2 2.0.20240424

### PR DESCRIPTION
**Pull request by showwin**
## AMI Update

This PR will also update the AMIs of the container instances as described in this [guide](https://www.notion.so/How-to-Update-AMI-using-Barcelona-78b6c47ab7a14b5184d7fcf1b54775b0):

[Release notes](https://docs.aws.amazon.com/AL2/latest/relnotes/relnotes-20240502.html)

[Amazon ECS-optimized AMIs - Amazon Elastic Container Service](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html)

ECS AMI SSM path: 
* https://ap-northeast-1.console.aws.amazon.com/systems-manager/parameters/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id/description?region=ap-northeast-1
* https://ap-northeast-1.console.aws.amazon.com/systems-manager/parameters/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/description?region=ap-northeast-1

And it also updates the AMI for the bastion image.

Bastion AMI SSM path: https://ap-northeast-1.console.aws.amazon.com/systems-manager/parameters/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2/description?region=ap-northeast-1

## Note
This time is not for security update but for Docker version update since the current version will be EOF.
https://app.asana.com/0/1206315055720505/1207252555665641/f

### CODE REVIEW

**Comment by degikko** [comment]
@ochko can you help us review this PR, please?

**Review by ochko — APPROVED** [review]
Looks good, Thanks!

**Comment by showwin** [comment]
Actually, we have to upgrade the AMI **after** May 16, 2024 when the latest AMI supports Docker 25.0.3...
I only updated ec-staging and staging district with this AMI.

**Comment by showwin** [comment]
I realized this should revert this change if we don't update AMI soon/

**Pull request merged**
