### PR TITLE
Control container count

### LINKED ISSUE #565: API to increase/decrease instance/container count
We need an API to increase and decrease instance or container counts in barcelona.

### PR DESCRIPTION
**Pull request by davidsiaw**
This PR introduces the ability to set container count using barcelona

Fixes #565

### CODE REVIEW

**Comment by degicat** [comment]
@essa please review this

**Comment by essa** [comment]
@davidsiaw 
Great!

I have tested it local and succeeded to increase task count by following command.

```
$ bcn api post /districts/essa-test/heritages/hello/services/web/count '{"desired_container_count": 3}' 
```

But I have an issue.

Before the command, task count is 1. So I expected this commands start two more tasks.
But it started three tasks and stopped the old task after new tasks started.

So, if we are running 80 tasks and increase it to 120, we need enough container instances for 200 (80+120) tasks to complete the update.

I think it's not critical, only we need more caution on available resources when we use this api.

@k2nr 
Do you know any workarounds for it?

**Comment by davidsiaw** [comment]
@essa Ah yes. I think I know why, because it creates a new task definition when it changes the task count. I can try and solve this situation in another PR

**Comment by essa** [comment]
@davidsiaw 

>I can try and solve this situation in another PR

Great!

Then LGTM for this PR.

**Review by essa — APPROVED** [review]

**Pull request merged**
