### PR TITLE
Apply rubocop for spec files

### PR DESCRIPTION
**Pull request by Yuuki77**
continuation of https://github.com/degica/barcelona/pull/678

now I apply rubocop for spec files 
these change are done by rubocop

### CODE REVIEW

**Comment by degicat** [comment]
@davidsiaw can you help us review this PR, please?

**Comment by davidsiaw** [comment]
@Yuuki77 can we avoid checking in the entire --auto-correct output for now? Its a lot of changes to review. We should just place the rules in and generate the rubocop_todo.yml and fix that up as we go.

**Comment by Yuuki77** [comment]
sure I just created ` .rubocop_todo.yml`

**Review by davidsiaw — APPROVED** [review]
Great! LGTM.

**Pull request merged**
