### PR TITLE
Refctor deploy runner job

### PR DESCRIPTION
**Pull request by k2nr**

### CODE REVIEW

**Comment by olingern** [comment]
Auto-retries for *all* redeploys is maybe too liberal. There are some cases where AWS resources are in such a state that we should _not_ automatically redeploy. 

I've had issues with[ ECS agent connections dropping](https://aws.amazon.com/premiumsupport/knowledge-center/ecs-agent-disconnected/) in the past, and the solution was to redeploy / kill the disconnected instance. I could see this retry logic being useful there, but not in all cases.

**Comment by k2nr** [comment]
This PR is a pure refactoring meaning there's no behavior change. Barcelona doesn't retry deployments. If there's an error it just stops.

**Comment by davidsiaw** [comment]
I fixed the conflict so I think this can already be merged.

**Comment by degicat** [comment]
@essa please review this

**Pull request merged**
