### PR TITLE
Add honeybadger to Barcelona

### PR DESCRIPTION
**Pull request by rramsden**
## Context

Pretty straight-forward, lets add some alerting so we can see what's happening.

image

### CODE REVIEW

**Comment by degicat** [comment]
@Iorin0225 please review this

**Comment by degicat** [comment]
@Yuuki77 please review this

**Comment by rramsden** [comment]
@davidsiaw Will assign you as a third reviewer here.

**Comment by k2nr** [comment]
hey don't forget this is a public repository

**Comment by rramsden** [comment]
@k2nr good point I will close this and roll keys

**Pull request closed without merging**
