### PR TITLE
Security Fixes

### PR DESCRIPTION
**Pull request by k2nr**
This PR fixes some security issues about the network stack.

## Automate yum update

- install `yum-cron-security` package to instances except for container instances
- run `yum update --security` at launch for container instances

`yum-cron-security` periodically (daily) installs security updates if available. The reason why I didn't install the package to container instances is that updating packages of running instance might break instance functionality (for example, if there is an update for `docker`, it updates `docker` and **restarts** the daemon which makes all running containers temporarily down). Instead, I added `yum update --security` to container instances' user data. Now that we have chaos, running container instances periodically get terminated by chaos and new instances has latest security updates.

## Install AWS inspector in pcidss instances

PCIDSS plugin adds NTP server and OSSEC manager server, I forgot to install Inspector agent in those instances

## Install AWS logs agent in bastion server

Fixes https://github.com/degica/barcelona/issues/373

## Connect bastion server to OSSEC (PCIDSS plugin)

Bastion should be monitored by OSSEC

### CODE REVIEW

**Comment by k2nr** [comment]
@essa I think you should review this. please take a look when you have time

**Comment by essa** [comment]
LGTM.

I think this has no influence on bgproduciton district.

**Comment by k2nr** [comment]
Found that bastion's available memory ran out because now bastion runs many services. I upgraded the instance type to `t2.micro` I'll see if `t2.micro` is enough for some days

**Comment by k2nr** [comment]
Thanks for your review! I haven't seen any issue so far but I'll wait until tomorrow and if there's no issue I'll apply this change to all of our districts

**Pull request merged**
