### PR TITLE
Add X-Request-Start to the reverse proxy headers

### PR DESCRIPTION
**Pull request by k2nr**
To gain capability to get E2E metric https://docs.newrelic.com/docs/apm/applications-menu/features/request-queue-server-configuration-examples

### CODE REVIEW

**Comment by k2nr** [comment]
@essa can you review this one?

**Comment by essa** [comment]
Sure!

**Comment by essa** [comment]
LGTM, it's useful! 👍

**Comment by k2nr** [comment]
Thanks, I need to have more tests. I'll merge after that

**Pull request merged**
