### PR TITLE
Change newrelic repo for amazon linux2

### PR DESCRIPTION
**Pull request by essa**
This PR changes the repository for newrelic agent.

- [Install Infrastructure for Linux \| New Relic Documentation](https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/installation/install-infrastructure-linux)

I confirmed it by replacing it and re-installing the package on an existing amazon linux2 host.

### CODE REVIEW

**Comment by k2nr** [comment]
I checked the repo file provided in the instruction and both baseurl and gpgkey use `https` now:

```
name=New Relic Infrastructure
baseurl=https://download.newrelic.com/infrastructure_agent/linux/yum/el/7/x86_64
gpgkey=https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
gpgcheck=1
repo_gpgcheck=1
```

Could you update to use https and test again?

**Comment by k2nr** [comment]
with the old repo, installtion copleted with some warnings. Thats why we didn't notice...

```
[   79.572939] cloud-init[4529]: Installing : newrelic-infra-1.3.5-1.x86_64                                1/1
[   79.579806] cloud-init[4529]: chdir /var/db/newrelic-infra/
[   79.580790] cloud-init[4529]: /var/tmp/rpm-tmp.u27q5L: line 56: initctl: command not found
[   79.582909] cloud-init[4529]: warning: %posttrans(newrelic-infra-0:1.3.5-1.x86_64) scriptlet failed, exit status 127
[   79.608530] cloud-init[4529]: Non-fatal POSTTRANS scriptlet failure in rpm package newrelic-infra-1.3.5-1.x86_64
[[32m  OK  [0m] Stopped Dynamically Generate Message Of The Day.
         Stopping Dynamically Generate Message Of The Day...
         Starting Dynamically Generate Message Of The Day...
[   79.700681] cloud-init[4529]: Verifying  : newrelic-infra-1.3.5-1.x86_64                                1/1
[   79.716404] cloud-init[4529]: Installed:
[   79.719604] cloud-init[4529]: newrelic-infra.x86_64 0:1.3.5-1
[   79.729957] cloud-init[4529]: Complete!
```

**Comment by essa** [comment]
@k2nr 
I tested it with `https` and updated this.

**Comment by k2nr** [comment]
Looks good to me :+1: thanks!

**Pull request merged**
