### PR TITLE
Add autoscaling

### PR DESCRIPTION
**Pull request by k2nr**

### CODE REVIEW

**Comment by k2nr** [comment]
I'll add another scaling statistic: 95th percentile of ALB's response time. turned out that this metric is fairly easy to support

**Comment by olingern** [comment]
@k2nr @rramsden Is this still being worked on / needed?

**Comment by k2nr** [comment]
Yes I think so. It's not priority and I don't have time to work on this :sweat:

**Comment by davidsiaw** [comment]
@k2nr I will be closing this PR since its really old and we are working on a new way to scale anyway

**Pull request closed without merging**
