### PR TITLE
AMI update to Amazon Linux 2 2.0.20231101.0

### PR DESCRIPTION
**Pull request by showwin**
## AMI Update

This PR will also update the AMIs of the container instances as described in this [guide](https://www.notion.so/How-to-Update-AMI-using-Barcelona-78b6c47ab7a14b5184d7fcf1b54775b0):

[Release notes](https://docs.aws.amazon.com/AL2/latest/relnotes/relnotes-20231103.html)

[Amazon ECS-optimized AMIs - Amazon Elastic Container Service](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-optimized_AMI.html)

ECS AMI SSM path: https://ap-northeast-1.console.aws.amazon.com/systems-manager/parameters/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/image_id/description?region=ap-northeast-1
https://ap-northeast-1.console.aws.amazon.com/systems-manager/parameters/aws/service/ecs/optimized-ami/amazon-linux-2/recommended/description?region=ap-northeast-1

And it also updates the AMI for the bastion image.

Bastion AMI SSM path: https://ap-northeast-1.console.aws.amazon.com/systems-manager/parameters/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2/description?region=ap-northeast-1

### CODE REVIEW

**Comment by degikko** [comment]
@davidsiaw can you help us review this PR, please?

**Review by davidsiaw — APPROVED** [review]
LGTM

**Comment by davidsiaw** [comment]
@showwin merged 👍

**Comment by showwin** [comment]
@davidsiaw Thanks for your quick review!

**Pull request merged**
