### PR TITLE
bundle update

### PR DESCRIPTION
**Pull request by k2nr**

### CODE REVIEW

**Comment by k2nr** [comment]
what's that crazy aws-sdk update...

**Comment by k2nr** [comment]
I see, there is a major version update that basically splits each AWS service into one gem. I think I can merge this if tests pass

**Comment by k2nr** [comment]
this includes rails update 5.0 -> 5.1 which is a little bit scary. tests passed and I confirmed it worked locally so going to merge

**Comment by greysteil** [comment]
Looks like you're pretty up-to-date after this - would you be up for automatically creating dependency update PRs in the future? I built [Dependabot](https://dependabot.com) at my last company to automatically create a PR each time a new dependency version is released. Could be a time-saver, and help you keep up-to-date? We made it totally free for open-source (of course!).

**Pull request merged**
