### PR TITLE
container instance update

### PR DESCRIPTION
**Pull request by k2nr**
**Do not merge for now**

- Container instances now use Amazon Linux 2 based optimized AMI
- Installs SSM agent

### CODE REVIEW

**Comment by essa** [comment]
> Installs SSM agent

Is this mean that we will get rid of `bcn ssh` but continue to use `bcn run`?

**Comment by k2nr** [comment]
You're right. Once we install ssm agent to all instances we can remove bcn ssh and we still need bastion servers to keep `bcn run` work

**Comment by essa** [comment]
I see.

LGTM 👍

**Comment by k2nr** [comment]
thanks. If you have an idea to get rid of bastion servers with SSM agent while keeping `bcn run` work, Please let me know.

Please don't merge this PR for now. I'd like to test Amazon Linux 2 with bastion servers first

**Comment by k2nr** [comment]
I thought I would test AL2 with bastion servers but turned out that this PR needs to be merge in order to make Barcelona work due to this https://github.com/degica/barcelona/blob/master/lib/barcelona/plugins/pcidss_plugin.rb#L383

I'm going to merge this. Let's test on staging

**Pull request merged**
