### PR TITLE
Fix deploy

### PR DESCRIPTION
**Pull request by essa**
This PR fixes deplyment on github-actions and velnerabilities.

### CODE REVIEW

**Comment by essa** [comment]
@davidsiaw 
Can you review this?

And merge it if you are OK.

**Comment by davidsiaw** [comment]
Ok, LGTM. will merge once CI passes

**Comment by davidsiaw** [comment]
@essa I think the update has changed rails enough to break the CI

**Comment by davidsiaw** [comment]
https://github.com/rails/sprockets-rails/issues/444 was the issue. I just added the manifest like it asked.

**Pull request merged**
